### ISSUE TITLE
Searching for a player should still work if they don't have stats for this season

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#203]
Currently you cannot search for a player on the rankings page without switching to a season where they have stats.

Search function should be improved to make it possible to find any player who has stats on W3C.

**Comment by marco93f** [comment]
This issue also applies for the match history page.

**Comment by marco93f** [comment]
There's still an issue for users that share the same nickname but have a different ID.
There are a couple players with the following accounts which are unranked for the current season, yet you can't search for them: ThunderHorn#2481, RoCK#22108, RoCK#22591.
If I were to guess, iIt's probably because of ThunderHorn#21132 and Rock#22264 being active during season 4.

**Comment by aaronjewell** [comment]
Should be resolved by w3champions/website-backend#125

It was an either/or. If ranked players were found for the season, display them. Otherwise link to the profiles of unranked. It will now merge the two result sets and display profiles for unranked and link to ranked players in the season table.
