### ISSUE TITLE
Tournament bracket ui broken

### ISSUE THREAD

**Issue by amacado** [w3champions/website#439]
The [/tournaments](https://www.w3champions.com/tournaments) page seems to be broken (no bracket is visible at all):
![image](https://user-images.githubusercontent.com/8781699/141367499-baabece0-45c7-4730-b290-6eaf2dbe295a.png)

This is caused by several `undefined index` and `duplicate keys` bugs which I was able to fix in #437.

After the UI fix the bracket is shown again, but the connectors are not in the right place as you can see here:
![image](https://user-images.githubusercontent.com/8781699/141367950-2d1e6665-e577-4f67-a862-2b1bbd6f391d.png)

I was able to trace the bug and wonder if this has worked in the past. Because if I traced it right, the [website backend](https://github.com/w3champions/website-backend)'s endpoint [/api/tournament](https://github.com/w3champions/website-backend/blob/b6a220d5307fc187fb0ddfc50d75beacc454dc1e/W3ChampionsStatisticService/Tournaments/TournamentsController.cs#L21) which is returning the `TournamentRound` object as property of the `Tournament` object do not contain the **`dimensions`** property which, is accessed in the UI (to calculate the connectors). 

While I think it's not be best idea to return data which is used in the UI for DOM manipulation, it does not even provide this data. I might traced it wrong, so please feel free to correct me.

**Comment by Cepheid-UK** [comment]
@abeninski designed this UI so I'm not that familiar with how its supposed to work, but even this is an improvement right now.

The reason I haven't prioritised this fix is because we're going to completely replace the tournaments view once automated tournaments are here.

It will display info about upcoming/current/completed automated tournaments, and I think it may be best to leave the end-of-season tournaments on liquipedia with a sidebar component.

**Comment by zygissss** [comment]
done
